release-to-candidate/action.yaml
test-snap-build/action.yaml

Found the first bug :man_facepalming: 
This ensures we just leave the output empty if no plugs/slots are decalred.

fix: ensure review outputs are blank if not populated

---

release-to-candidate/action.yaml

There was a slight typo in the release workflow which meant that the `classic` argument wasn't being passed correctly to the `review-tools` action.
Symptom is seen [here](https://github.com/jnsgruk/terraform/actions/runs/7085496875/job/19282764871#step:2:296). 
Drive-by to pass the plugs/slots declarations in where appropriate too, which I missed on the last pass.

fix: get classic input from 'parse' step in release job

---

promote-to-stable/action.yaml

This PR aims to ensure that the `promote-to-stable` action will only promote revisions that are explicitly mentioned for promotion in the call-for-testing issue.
It works by parsing the `/promote <rev>,... stable done` command example in the call for testing issue.

feat: only promote revisions mentioned in the call for testing

---

README.md
call-for-testing/action.yaml
get-architectures/action.yaml
get-screenshots/action.yaml
parse-snapcraft-yaml/README.md
parse-snapcraft-yaml/action.yaml
promote-to-stable/action.yaml
release-to-candidate/action.yaml
sync-version/action.yaml
test-snap-build/action.yaml

**Note**: This PR should only be reviewed once #16 is merged as this is based off that branch.
The duplication of code for finding and parsing the snapcraft.yaml was bothering me, so I've introduced a new action named `parse-snapcraft-yaml` which centralises that logic, and then adjusted the other workflows to use it, so this PR is a reduction in lines of code overall, even with the addition of a new README :slightly_smiling_face:. It also means we won't have multiple files to update each time we want to use a field from the `snapcraft.yaml` in a new way.

feat: add parse-snapcraft-yaml action

---

parse-snapcraft-yaml/README.md
parse-snapcraft-yaml/action.yaml

Don't checkout the source code in the internal action for parsing the snapcraft.yaml, because if it's already been checked out earlier then doing it again will clobber any credentials that have already been set up.

fix: don't checkout the source in parse-snapcraft-yaml action

---

get-screenshots/action.yaml
setup-ghvmctl/README.md

See: https://github.com/snapcrafters/ghvmctl/pull/3

cleanup: Do not use deprecated ghvmctl snap commands

---

call-for-testing/action.yaml
fetch-manifests/README.md
fetch-manifests/action.yaml
get-screenshots/action.yaml
release-to-candidate/action.yaml
setup-ghvmctl/README.md

There is a new release of the `upload-artifact` and `download-artifact` actions provided by Github that come with a [breaking change](https://github.com/actions/upload-artifact#breaking-changes) for us. We were previously relying on being able to have multiple jobs upload the same artifact name, and have Github automatically coalesce them.
This no longer works, but with the trade-off that artifacts are now available from the REST API immediately after the step that creates them completes.
The following implements the logic to fetch all of the artifacts from a given workflow run, and unzip them in place. This is actually how I had intended to do this before, but was hit by API limitations.
There is a demo workflow run [here](https://github.com/jnsgruk/ci-testing/actions/runs/7223794512) …

feat: use upload-artifacts@v4

---

get-screenshots/action.yaml

Fixes https://github.com/snapcrafters/.github/issues/17.
When we moved to allow multiple screenshots, we ended up committing a bunch of symlinks that didn't resolve properly in the screenshots repo. This fixes that problem.

fix: copy target of screenshot symlinks when committing

---

release-to-candidate/README.md
release-to-candidate/action.yaml

Hey :wave: 
So as discussed in our catch-up meet, here is a first draft of how we might want to create tags automatically in repositories based on the revisions that were released to the store. The aim here is to make debugging issues a little easier, as when an issue is reported on a snap with a given revision, you can just checkout the tag and build/install/troubleshoot.
It's a little complicated with multiple architectures. The design I've chosen is to create one tag per revision, and name with the arch just to make searching/bisecting easier. The tag names will be `rev<num>/<arch>`.
You can see an example run [here](https://github.com/jnsgruk/ci-testing/actions/runs/7222177075) and the resulting tags [here](https://github.com/jnsgruk/ci-testing/tags).
I should note that this is …

feat: create tags for new revisions published to the store

---

call-for-testing/README.md
call-for-testing/action.yaml
promote-to-stable/README.md
promote-to-stable/action.yaml
release-to-candidate/README.md
release-to-candidate/action.yaml
test-snap-build/README.md
test-snap-build/action.yaml

Some snaps cannot be built with the `latest/stable` snapcraft, for example those that rely on `core18`.
This change enables developers to specify which channel they wish to use when installing snapcraft.

feat: enable `snapcraft-channel` to be passed to actions

---

call-for-testing/README.md
call-for-testing/action.yaml
call-for-testing/template.md
get-screenshots/README.md
get-screenshots/action.yaml
promote-to-stable/README.md
promote-to-stable/action.yaml
release-to-candidate/README.md
release-to-candidate/action.yaml
sync-version/README.md
sync-version/action.yaml

This is a first stab at making these workflows more channel agnostic.
Until this point, only `latest/candidate` and `latest/stable` were considered. In this commit, we formalise that as `latest/candidate` as the default in all places, which should be backwards compatible. We also introduce `channel` as an input in more places and thread it through where necessary.
I *think* this is all that is needed to ensure that snaps such as `gimp` can run multiple tracks/channels.

feat: enable building/promoting to tracks other than `latest`

---

call-for-testing/template.md

Just noticed this mistake in a new call for testing, `$` is not required here.

fix: remove extraneous $ in templates

---

get-screenshots/README.md
get-screenshots/action.yaml

Allows the specification of an application name to execute inside the snap when taking screenshots.
Helps when the snap has a different "app name" to "snap name". E.g. the `sublime-text` snap only has an app named `subl` defined, which led to this failure in CI: https://github.com/snapcrafters/sublime-text/actions/runs/7844422700/job/21407033718#step:2:292

feat: allow specification of app inside snap to screenshot

---

release-to-candidate/action.yaml

Ensure that we update the archs, rather than remove - such that each build gets a new hash and we don't get collisions in Launchpad's backend.

fix: update architectures in snapcraft yaml rather than remove

---

release-to-candidate/README.md
release-to-candidate/action.yaml

1. This PR now adds support to use the new backend of snapcraft remote-build. The build seems significantly better. Also allows the `lint` and other keywords on the toplevel that were `core22` only.
2. Fixes the `project_root`  not being used while reviewing the snap file
3. adds a new input named `show-build-log` which is `true` by default and shows the build log on success if true.

feat: new remote-builder backend and misc improvement

---

get-architectures/action.yaml
release-to-candidate/action.yaml

core24 now uses the `platforms` keyword for specifying the build architecture for snaps rather than the `architectures` keyword. This pull request updates the get-architectures and release-to-candidate actions to support using the `platforms` top-level key to determine which arches to build the snap for.
Also, the remote-build command, when building core24 snaps, will use the `--platforms` flag rather than the `--build-for` flag.

feat: Add support for building + releasing core24 based snaps

---

get-screenshots/README.md
get-screenshots/action.yaml
release-to-candidate/README.md
release-to-candidate/action.yaml
sync-version/README.md
sync-version/action.yaml

Fixes #39 
This should make the actions more reusable by people *other* than Snapcrafters.

feat: make bot name/email configurable

---

call-for-testing/action.yaml
call-for-testing/template.md

Environment variable substitution in the call for testing stopped working since we factored out the testing instructions. This fix ensures that the template gets the various sections substituted out before rendering, to ensure that all the relevant fields get templated correctly.
See example output here: https://github.com/jnsgruk/ci-testing/issues/51

fix: correctly substitute testing instructions in issue template

---

release-to-candidate/action.yaml

This PR makes some necessary changes to make core24 snaps build with remote build.
1. disables force-fallback
2. restricts other architectures

ci: changes for core24 snaps to build

---

parse-snapcraft-yaml/README.md
parse-snapcraft-yaml/action.yaml
release-to-candidate/action.yaml

This adds support for automatically detecting any [snap components](https://documentation.ubuntu.com/snapcraft/8.6.2/howto/components/) defined in a snap's `snapcraft.yaml`, and if found, uploading those components along with the snap to the store.
Side note: I updated from `snap push` to `snap upload` as the latter is now preferred and the former is being deprecated.
In parallel, I have asked the Snap Store team to grant permissions for snap components to be uploaded if published under `snapcrafters`.
Note I have tested the commands locally but have NOT tested from a GitHub action pointed at my fork. I can do so for testing a snap WITHOUT components, but do not have permissions in the store needed to test uploads for a snap with components.

feat: support uploading snap components

---

run-tests/action.yaml

This allows running the tests on multiple architectures, so we can use GitHub's ARM runners to test on ARM.
Fixes [this behaviour](https://github.com/snapcrafters/ruff/actions/runs/17565385552/job/49904778894).

fix(run-tests): allow running on multiple architectures

---

release-to-candidate/action.yaml

Switches from mangling the architecture/platforms in the yaml file before we build them, to just using the newly supported `--build-for`. Because the new backend is much more stable and capable, we can remove all of the workarounds and conditionals around "fallback" modes etc.
This reduces the complexity of the code a fair bit, and means we don't have to modify the source of a snap recipe before we build the snap for a given architecture.
The one change any snaps might have to make is to use a condensed format for specifying architectures/platforms, i.e.
```
platforms:
arm64:
amd64:
architectures:
- arm64
- amd64
```
But most of our snaps already do this, and the rest will be easy to adjust.
I tested this on `core20`, `core22` and `core24`.

feat: use `--build-for` when building snaps for single arch
